name: AndroidCI

on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch Name'
        required: true
        default: 'master'
        options:
          - 'master'
          - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK to GitHub Release
        uses: actions/upload-artifact@v4
        with:
          path: app/release/app-release.apk
          name: app-release
