name: AndroidCI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.2

      - name: Set up JDK 8
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v4.3.1
        env:
          GITHUB_TOKEN: "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"
        with:
          asset_path: app/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
