name: AndroidCI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.2
      - name: Set up JDK 8
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Upload APK to GitHub Release
        uses: actions/upload-release-asset@4.3.1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./app/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive